### ISSUE TITLE
Dynamics node table error

### ISSUE THREAD

**Issue by ban3bbal000** [luckylyk/ncachemanager#1]
Hi,

First of all really awesome cache manager. I started testing it this week and I run into a small bug regarding the dynamic nodes table. Although the tool works fine, the cache's panel always shows out of workspace error and the range cached is invisible. The error solves itself when I reference the Maya scene into a new scene.

**Comment by luckylyk** [comment]
how damn, i forgot to subscribe as viewer to that repository and i missed your message.
I will check that asap !

**Comment by luckylyk** [comment]
Question, are you using windows, or maya ? You have that everytime ? Even if you edit the workspace ?
